### ISSUE TITLE
errors?

### ISSUE THREAD

**Issue by giovannidanelli** [angelopasquale/matheng-notes-issues#1]
pag 5, dopo la definizione 1.1.5, le proprieta 2 e 4 hanno a sx lo stesso membro, è giusto?

pag 6, dopo la definizione 1.2.1, dove c'è scritto per la prima volta " (x,x') in G(r) ", è giusto? credo che sia " (x,x') non in G(r) ".

**Comment by michelebucelli** [comment]
E' giusto in entrambi i casi. Pubblicherò la correzione a breve.
