### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by giovannidanelli** [angelopasquale/matheng-notes-issues#3]
pag 23, terza riga. si dice che {En} è una partition, ma come fa essere una partition se qualche riga dopo si dice che E1 è incluso in E2 che è inluso in E3 e così via. forse si intendeva una semplice covering ?

**Comment by michelebucelli** [comment]
Sì, {E_n} è un covering più che una partition di \Omega. Correggo e pubblico la correzione a breve.
